#! /bin/bash
: '
   Terminal background Color Utility 

    				-->   [ Author ]  Viki (a) Vignesh Natarajan 
				-->   [ Domain ]  https://vikiworks.io 
'
usage(){
    echo
    echo "Usage: bgcolor <color_name>"
    echo
    echo
    echo "Example: bgcolor green"
    echo
    echo "list of supported colors :"
    echo
    echo "	-> black"
    echo "	-> red"
    echo "	-> green"
    echo "	-> orange"
    echo "	-> blue"
    echo "	-> magenta"
    echo "	-> cyan"
    echo "	-> grey"
    echo "	-> default"
    echo
    echo
}

if [ -z "$1" ]; then
    usage
    exit 1
fi

SET_BG_COLOR(){
    COLOR="$1"
    echo "PS1=\`printf \"%s\" \"\033[4${COLOR}m\u@\h\$\033[39m\"\`" >> ~/.bashrc
}

case $1 in
   black ) 	SET_BG_COLOR "0"; ;;
   red ) 	SET_BG_COLOR "1"; ;;
   green ) 	SET_BG_COLOR "2"; ;;
   orange ) 	SET_BG_COLOR "3"; ;;
   blue ) 	SET_BG_COLOR "4"; ;;
   magenta ) 	SET_BG_COLOR "5"; ;;
   cyan ) 	SET_BG_COLOR "6";  ;;
   grey ) 	SET_BG_COLOR "7";  ;;
   default ) 	SET_BG_COLOR "9";  ;;
   *     )	usage; 		exit;;
esac

bash
